spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gvardianez/MyMarket/
          search-paths:
            - "ms-configs/{application}"
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: false

